# Generated by Django 6.0.4 on 2026-04-10 07:56

import apps.customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_country_alter_company_is_vat_group_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(help_text='The company that owns this customer record.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='AE', help_text='ISO 3166-1 alpha-2 country code.', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2g', 'B2G'), ('b2c', 'B2C')], db_index=True, default='b2b', help_text='B2B and B2G are in scope for Phase 1 UAE e-invoicing (Q2 2026).', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Legal registered name. Defaults to name if not provided.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Trading / display name of the customer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='peppol_endpoint',
            field=models.CharField(blank=True, default='', help_text='PEPPOL participant ID if buyer is on the PEPPOL network. For overseas customers already registered in their home country.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_province',
            field=models.CharField(blank=True, default='', help_text='State or province — used for non-UAE customers.', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Auto-derived: first 10 digits of TRN. Used as B2B identifier.', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trn',
            field=models.CharField(blank=True, default='', help_text='UAE TRN — 15 digits. Required for UAE B2B customers.', max_length=15, validators=[apps.customers.models.validate_trn]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, default='', help_text='VAT registration number for international (non-UAE) customers.', max_length=20, validators=[apps.customers.models.validate_vat_number]),
        ),
    ]
