# Generated by Django 6.0.4 on 2026-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_company_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Customer company logo (JPG or PNG).', null=True, upload_to='customer_logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trn_document',
            field=models.FileField(blank=True, help_text='TRN / tax registration certificate (PDF, JPG or PNG).', null=True, upload_to='customer_trn/%Y/%m/'),
        ),
    ]
