# Generated by Django 6.0.4 on 2026-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_logo_customer_trn_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trn_expiry_date',
            field=models.DateField(blank=True, help_text='Customer TRN expiry / validity end date (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='trn_issue_date',
            field=models.DateField(blank=True, help_text="Date the customer's Tax Registration (TRN) was issued.", null=True),
        ),
    ]
