# Generated by Django 5.0.4 on 2026-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_trn_expiry_date_customer_trn_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="legal_registration_authority",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Issuing authority of the legal registration (BTAE-12). Required when legal_registration_type is Trade License (rule ibr-172-ae).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="legal_registration_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Buyer legal entity registration number (e.g. trade license, CR number). Used in UBL PartyLegalEntity/CompanyID (BTAE-11).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="legal_registration_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TL", "Trade License (TL)"),
                    ("CRN", "Commercial Registration Number (CRN)"),
                    ("EID", "Emirates ID (EID)"),
                    ("PAS", "Passport (PAS)"),
                    ("CD", "Commercial Document (CD)"),
                ],
                default="",
                help_text="Type of legal registration document (TL=Trade License, CRN=CR Number, etc.). Used as schemeAgencyID on PartyLegalEntity/CompanyID (BTAE-15).",
                max_length=5,
            ),
        ),
    ]
