# Generated by Django 5.0.4 on 2026-07-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_legal_registration_authority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='legal_registration_authority',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='legal_registration_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='legal_registration_type',
        ),
    ]
