# Generated by Django 6.0.4 on 2026-04-17 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_groups_and_more'),
    ]

    def mark_existing_verified(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        User.objects.all().update(email_verified=True)

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once the user has clicked the email verification link.'),
        ),
        migrations.RunPython(mark_existing_verified, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('inbound_supplier', 'Inbound Supplier')], db_index=True, default='supplier', help_text='Platform-level default role. Per-company role is in CompanyMember.', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_verification_tokens',
            },
        ),
    ]
