# Generated by Django 6.0.4 on 2026-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mfa_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='True when TOTP-based MFA is active for this account.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 TOTP secret. Populated during MFA setup, retained after enable.', max_length=64),
        ),
    ]
