# Generated by Django 6.0.4 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_mfa_enabled_alter_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('inbound_supplier', 'Inbound Supplier'), ('buyer', 'Buyer')], db_index=True, default='supplier', help_text='Platform-level default role. Per-company role is in CompanyMember.', max_length=20),
        ),
    ]
