# Generated by Django 6.0.4 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='AE', help_text='ISO 3166-1 alpha-2 country code.', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_vat_group',
            field=models.BooleanField(default=False, help_text='True if this entity is a member of a VAT group (shares group TRN).'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(help_text='Legal / registered name as per trade license.', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Trading name of the business.', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='peppol_endpoint',
            field=models.CharField(blank=True, default='', help_text='PEPPOL participant ID assigned by ASP (e.g. 0088:1234567890123).', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='tin',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-derived: first 10 digits of TRN. Used as B2B business identifier.', max_length=10),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='admin', help_text='Role within this specific company (overrides User.role).', max_length=20),
        ),
    ]
