# Generated by Django 6.0.4 on 2026-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_country_alter_company_is_vat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('inbound_supplier', 'Inbound Supplier')], default='admin', help_text='Role within this specific company (overrides User.role).', max_length=20),
        ),
    ]
