# Generated by Django 6.0.4 on 2026-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_legal_registration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legal_registration_id',
            field=models.CharField(blank=True, default='', help_text='Legal entity registration number (e.g. trade license number, CR number). Used in UBL PartyLegalEntity/CompanyID.', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_registration_type',
            field=models.CharField(blank=True, choices=[('TL', 'Trade License (TL)'), ('CRN', 'Commercial Registration Number (CRN)'), ('EID', 'Emirates ID (EID)'), ('PAS', 'Passport (PAS)'), ('CD', 'Commercial Document (CD)')], default='', help_text='Type of legal registration document (TL=Trade License, CRN=CR Number, etc.). Used as schemeID attribute on PartyLegalEntity/CompanyID.', max_length=5),
        ),
    ]
