# Generated by Django 6.0.4 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_legal_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('inbound_supplier', 'Inbound Supplier'), ('buyer', 'Buyer')], default='admin', help_text='Role within this specific company (overrides User.role).', max_length=20),
        ),
    ]
