# Generated by Django 6.0.4 on 2026-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (PNG/JPG).', null=True, upload_to='company_logos/'),
        ),
    ]
