# Generated by Django 6.0.4 on 2026-06-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trn_expiry_date',
            field=models.DateField(blank=True, help_text='TRN expiry / validity end date (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trn_issue_date',
            field=models.DateField(blank=True, help_text='Date the Tax Registration (TRN) was issued.', null=True),
        ),
    ]
