# Generated by Django 6.0.4 on 2026-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_trn_expiry_date_company_trn_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='iban',
            field=models.CharField(blank=True, default='', help_text='IBAN — used as UBL PayeeFinancialAccount/ID (IBT-084).', max_length=34),
        ),
        migrations.AddField(
            model_name='company',
            name='swift_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
