# Generated by Django 6.0.4 on 2026-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_bank_account_number_company_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_registration_authority',
            field=models.CharField(blank=True, default='', help_text='Issuing authority of the legal registration (BTAE-12). UAE rule ibr-172-ae requires this when the registration type is Trade License (e.g. "Department of Economic Development").', max_length=150),
        ),
    ]
