# Generated by Django 6.0.4 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspsubmissionlog',
            name='response_payload',
            field=models.JSONField(blank=True, help_text='Complete raw JSON response from the ASP (sanitized, no PII).', null=True),
        ),
    ]
