# Generated by Django 6.0.4 on 2026-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_certificate_webhook_peppol'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppolmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='key_reference',
            field=models.CharField(blank=True, default='', help_text='Filesystem: path to private key file. KMS: key ARN. Vault: secret path. Never store the key material itself here.', max_length=500),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='events',
            field=models.JSONField(default=list, help_text='List of event types to deliver (e.g. ["invoice.validated", "invoice.rejected"]).'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='name',
            field=models.CharField(help_text='Human-readable name for this webhook (e.g. "ERP System", "Accounting App").', max_length=100),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(help_text='HMAC-SHA256 secret. Used to sign payloads. Never expose via API after creation.', max_length=128),
        ),
    ]
