# Generated by Django 6.0.4 on 2026-04-10 07:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_country_alter_company_is_vat_group_and_more'),
        ('customers', '0002_alter_customer_company_alter_customer_country_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date', '-invoice_sequence'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='asp_response',
            field=models.JSONField(blank=True, help_text='Raw JSON response from ASP (accepted/rejected + details).', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='asp_submission_id',
            field=models.CharField(blank=True, default='', help_text='Transaction ID returned by ASP after submission.', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text='Supplier / issuing company.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='Buyer / invoice recipient.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoice-level discount applied before VAT calculation.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to AED. Always 1.0 for AED invoices.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, help_text='Auto-generated unique invoice number (e.g. INV-202601-000001).', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Sequential number per company. Used to generate invoice_number.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('simplified', 'Simplified Invoice'), ('credit_note', 'Credit Note')], default='tax_invoice', help_text='Tax Invoice (standard B2B) or Credit Note (per Article 65).', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Invoice issue date (date of supply for VAT purposes).'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order_number',
            field=models.CharField(blank=True, default='', help_text='Buyer PO number for reference.', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, default='', help_text='Original invoice number (required for credit notes).', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all item amounts before VAT.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supply_date',
            field=models.DateField(blank=True, help_text='Date of supply (tax point). Defaults to issue_date if not set.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal − discount_amount. VAT is calculated on this.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total: taxable_amount + total_vat.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total VAT across all line items.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2g', 'B2G'), ('b2c', 'B2C')], default='b2b', help_text='B2B and B2G are mandatory Phase 1 scope (UAE MoF, Q2 2026).', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xml_file',
            field=models.FileField(blank=True, help_text='Generated PEPPOL UBL 2.1 XML file path in media storage.', null=True, upload_to='invoices/xml/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quantity (supports fractional units).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order of items on the invoice.'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='quantity × unit_price, before VAT.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='subtotal + vat_amount.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of measure (e.g. pcs, hrs, kg). Optional.', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Price per unit (before VAT).', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount for this line item.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Actual VAT percentage applied (e.g. 5.00 for standard rate).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate_type',
            field=models.CharField(choices=[('standard', 'Standard Rate (5%)'), ('zero', 'Zero Rate (0%)'), ('exempt', 'Exempt'), ('out_of_scope', 'Out of Scope')], default='standard', help_text='Determines the VAT rate applied to this line item.', max_length=20),
        ),
    ]
