# Generated by Django 6.0.4 on 2026-04-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_fta_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract_reference',
            field=models.CharField(blank=True, default='', help_text='Contract document reference (Continuous Supplies — ContractDocumentReference/ID).', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supply_date_end',
            field=models.DateField(blank=True, help_text='End of supply period (Continuous Supplies only — maps to InvoicePeriod/EndDate).', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('credit_note', 'Credit Note'), ('commercial_invoice', 'Commercial Invoice'), ('continuous_supply', 'Continuous Supply'), ('simplified', 'Simplified Invoice')], default='tax_invoice', help_text='Tax Invoice (standard B2B) or Credit Note (per Article 65).', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supply_date',
            field=models.DateField(blank=True, help_text='Date of supply / tax point date. For continuous supplies this is the period start.', null=True),
        ),
    ]
