# Generated by Django 6.0.4 on 2026-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_mandatory_uae_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_means_code',
            field=models.CharField(choices=[('10', 'Cash (10)'), ('20', 'Cheque (20)'), ('30', 'Credit Transfer (30)'), ('48', 'Bank Card (48)'), ('49', 'Direct Debit (49)'), ('57', 'Standing Order (57)'), ('58', 'SEPA Credit Transfer (58)')], default='30', help_text='UN/ECE UNCL 4461 payment means code (e.g. 30=Credit Transfer, 10=Cash). Mandatory in UBL PaymentMeans element.', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(blank=True, default='', help_text='Short product/service name (UBL Item/Name, max 150 chars). If blank, falls back to the first 80 chars of description in XML.', max_length=150),
        ),
    ]
