# Generated by Django 6.0.4 on 2026-04-28 11:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_payment_means_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid by the buyer (sum of all Payment records).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Submission'), ('submitted', 'Submitted to ASP'), ('validated', 'Validated by ASP'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], db_index=True, default='draft', max_length=20),
        ),
    ]
