# Generated by Django 6.0.4 on 2026-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_amount_paid_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_viewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when a buyer first opened this invoice via the Buyer Portal.', null=True),
        ),
    ]
