# Generated by Django 6.0.4 on 2026-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_peppol_fta_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='idx_invoice_peppol_fta',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fta_reference',
            field=models.CharField(blank=True, default='', help_text='FTA-assigned reference number after successful reporting.', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fta_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Reporting'), ('reported', 'Reported to FTA'), ('error', 'Reporting Error')], db_index=True, help_text='FTA reporting status (Corner 5 in PEPPOL 5-corner model).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Submission'), ('processing', 'Processing'), ('submitted', 'Submitted to ASP'), ('validated', 'Validated by ASP'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], db_index=True, default='draft', max_length=20),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='peppol_message_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='peppol_status',
        ),
    ]
