# Generated by Django 6.0.4 on 2026-05-25 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_fraud_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicefraudalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice Fraud Alert', 'verbose_name_plural': 'Invoice Fraud Alerts'},
        ),
        migrations.AlterField(
            model_name='invoicefraudalert',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', help_text='LLM-generated explanation (high-risk invoices only).'),
        ),
        migrations.AlterField(
            model_name='invoicefraudalert',
            name='duplicate_invoice_ids',
            field=models.JSONField(default=list, help_text='UUIDs of invoices considered duplicates of this one.'),
        ),
        migrations.AlterField(
            model_name='invoicefraudalert',
            name='flags_json',
            field=models.JSONField(default=list, help_text='List of FraudFlag dicts: {code, description, severity, category}.'),
        ),
        migrations.AlterField(
            model_name='invoicefraudalert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicefraudalert',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Composite fraud risk score 0.0–1.0.'),
        ),
    ]
