# Generated by Django 6.0.4 on 2026-06-05 07:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_logo'),
        ('invoices', '0013_alter_invoicefraudalert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, help_text='Auto-generated invoice number, unique per company (e.g. INV-202601-000001).', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Sequential number per company. Used to generate invoice_number. Never reset.'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate_type', models.CharField(choices=[('standard', 'Standard Rate (5%)'), ('zero', 'Zero Rate (0%)'), ('exempt', 'Exempt'), ('out_of_scope', 'Out of Scope')], default='standard', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Owning company. Null = global catalog item (admin-managed).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='idx_product_company_active')],
            },
        ),
    ]
