# Generated by Django 6.0.4 on 2026-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deactivation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by the user when the invoice was deactivated.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Submission'), ('processing', 'Processing'), ('submitted', 'Submitted to ASP'), ('validated', 'Validated by ASP'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('deactivated', 'Deactivated')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Invoice Created'), ('updated', 'Invoice Updated'), ('submitted', 'Submitted for Processing'), ('validated', 'Validated by ASP'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('deactivated', 'Deactivated'), ('paid', 'Marked Paid'), ('xml_generated', 'XML Generated'), ('asp_sent', 'Sent to ASP'), ('fta_reported', 'Reported to FTA'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_removed', 'Item Removed'), ('deleted', 'Invoice Deleted')], db_index=True, max_length=30),
        ),
    ]
