# Generated by Django 6.0.4 on 2026-06-22 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_legal_registration_authority'),
        ('invoices', '0015_invoice_deactivated_at_invoice_deactivation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('form_type', models.CharField(default='pint', help_text="Which create form this draft belongs to: 'pint' or 'new'.", max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Raw form snapshot (JSON).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_drafts', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'form_type'], name='idx_invoice_draft_user_form')],
                'constraints': [models.UniqueConstraint(fields=('user', 'company', 'form_type'), name='uniq_invoice_draft_user_company_form')],
            },
        ),
    ]
