# Generated by Django 6.0.4 on 2026-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoicedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_approval_note',
            field=models.TextField(blank=True, default='', help_text='Buyer note / reason (e.g. on rejection).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_signature_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address captured at the time of the buyer e-signature.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the buyer approved & e-signed the invoice.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_signed_name',
            field=models.CharField(blank=True, default='', help_text='Name the buyer typed when e-signing / confirming the order.', max_length=160),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Buyer Approval'), ('pending', 'Pending Submission'), ('processing', 'Processing'), ('submitted', 'Submitted to ASP'), ('validated', 'Validated by ASP'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('deactivated', 'Deactivated')], db_index=True, default='draft', max_length=20),
        ),
    ]
