# Generated by Django 6.0.6 on 2026-07-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_trn_expiry_date_customer_trn_issue_date'),
        ('invoices', '0017_invoice_buyer_approval_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Buyer / invoice recipient.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
    ]
