# Generated by Django 6.0.6 on 2026-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_make_customer_nullable_for_early_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='form_payload',
            field=models.JSONField(blank=True, default=None, help_text='Full form snapshot for early-draft invoices that the user has not yet submitted. Stores PINT-field values, line items, and UI state so the form can be resumed from any device.', null=True),
        ),
    ]
