# Generated by Django 5.0.4 on 2026-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0020_add_buyer_signature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="accounts_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("receivable", "Accounts Receivable (AR)"),
                    ("payable", "Accounts Payable (AP)"),
                ],
                default="",
                help_text="FTA Audit File ledger classification — Accounts Receivable (AR) or Accounts Payable (AP).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="supplier_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Supplier (seller) location as recorded for the FTA Audit File, e.g. "Dubai, UAE".',
                max_length=255,
            ),
        ),
    ]
