# Generated by Django 5.0.4 on 2026-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0020_add_buyer_signature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_means_code",
            field=models.CharField(
                choices=[
                    ("10", "Cash"),
                    ("20", "Cheque"),
                    ("30", "Credit Transfer"),
                    ("48", "Bank Card"),
                    ("49", "Direct Debit"),
                    ("57", "Standing Order"),
                    ("58", "SEPA Credit Transfer"),
                ],
                default="30",
                help_text="UN/ECE UNCL 4461 payment means code (e.g. 30=Credit Transfer, 10=Cash). Mandatory in UBL PaymentMeans element.",
                max_length=5,
            ),
        ),
    ]
