# Generated by Django 5.0.4 on 2026-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0021_invoice_accounts_type_invoice_supplier_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="item_classification_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HS classification code. Required when item_type is Goods or Both (rule ibr-184/186-ae).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "Goods"),
                    ("S", "Services"),
                    ("B", "Both — Goods and Services"),
                ],
                default="",
                help_text="Goods (G), Services (S), or Both (B) — UBL CommodityClassification/CommodityCode.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="service_accounting_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Service accounting code (BTAE-17, scheme SAC). Required when item_type is Services or Both (rule ibr-185/186-ae).",
                max_length=50,
            ),
        ),
    ]
