# Generated by Django 5.0.4 on 2026-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0022_invoiceitem_item_classification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="credit_note_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "DL8.61.1.A",
                        "Cancellation of the supply after the tax invoice was issued",
                    ),
                    (
                        "DL8.61.1.B",
                        "Essential change or alteration in the nature of the supply",
                    ),
                    (
                        "DL8.61.1.C",
                        "Change in the previously agreed consideration (e.g. discount)",
                    ),
                    ("DL8.61.1.D", "Full or partial return of the goods or services"),
                    (
                        "DL8.61.1.E",
                        "Taxable amount or VAT amount on the tax invoice was incorrect",
                    ),
                    ("VD", "Void — the entire invoice is cancelled"),
                ],
                default="",
                help_text="BTAE-03 — reason for the credit note, per UAE VAT Executive Regulation Article 61(1). Required for credit notes (rule ibr-158-ae).",
                max_length=15,
            ),
        ),
    ]
