# Generated by Django 5.0.4 on 2026-07-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_alter_invoice_payment_means_code'),
        ('invoices', '0023_invoice_credit_note_reason_code'),
    ]

    operations = [
    ]
