# Generated by Django 6.0.4 on 2026-04-15 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_country_alter_company_is_vat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('api', 'API Submission'), ('email', 'Email Ingestion'), ('peppol', 'PEPPOL Network')], default='api', max_length=10)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('received', 'Received'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('pending_review', 'Pending Internal Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fta_submitted', 'Submitted to FTA'), ('fta_accepted', 'FTA Accepted'), ('fta_rejected', 'FTA Rejected')], db_index=True, default='received', max_length=30)),
                ('supplier_invoice_number', models.CharField(db_index=True, help_text='Invoice number as assigned by the supplier.', max_length=100)),
                ('invoice_type', models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('credit_note', 'Credit Note'), ('commercial_invoice', 'Commercial Invoice'), ('continuous_supply', 'Continuous Supply'), ('simplified', 'Simplified Invoice')], default='tax_invoice', max_length=20)),
                ('transaction_type', models.CharField(choices=[('b2b', 'B2B'), ('b2g', 'B2G'), ('b2c', 'B2C')], default='b2b', max_length=10)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('AED', 'UAE Dirham (AED)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='AED', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('purchase_order_ref', models.CharField(blank=True, default='', max_length=100)),
                ('contract_ref', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_xml', models.TextField(blank=True, default='', help_text='Original UBL XML as submitted by the supplier.')),
                ('raw_json', models.JSONField(blank=True, help_text='Parsed JSON payload if submitted via API (non-XML path).', null=True)),
                ('attachment', models.FileField(blank=True, help_text='PDF or XML attachment received by email.', null=True, upload_to='inbound/attachments/%Y/%m/')),
                ('validation_score', models.SmallIntegerField(blank=True, help_text='0–100 score after validation (100 = fully compliant).', null=True)),
                ('has_critical_errors', models.BooleanField(default=False)),
                ('observation_sent_at', models.DateTimeField(blank=True, help_text='When the observation email was last sent to supplier.', null=True)),
                ('observation_count', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('fta_submission_id', models.CharField(blank=True, default='', max_length=255)),
                ('fta_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('fta_response', models.JSONField(blank=True, null=True)),
                ('receiving_company', models.ForeignKey(help_text='Our company that received this invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='received_invoices', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inbound_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbound Invoice',
                'verbose_name_plural': 'Inbound Invoices',
                'db_table': 'inbound_invoices',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('event', models.CharField(help_text='Short description of what happened (e.g. "Validation passed").', max_length=100)),
                ('detail', models.JSONField(blank=True, help_text='Extra data (observation counts, FTA response, etc.).', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the change. Null = system/Celery.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='inbound.inboundinvoice')),
            ],
            options={
                'db_table': 'inbound_audit_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InboundInvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbound.inboundinvoice')),
            ],
            options={
                'db_table': 'inbound_invoice_items',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='InboundObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_code', models.CharField(help_text='Validation rule identifier (e.g. V001, FAF-VAT-01).', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('info', 'Info')], max_length=10)),
                ('field_name', models.CharField(blank=True, default='', help_text='The specific field that triggered this observation.', max_length=100)),
                ('message', models.TextField(help_text='Human-readable description of the issue.')),
                ('suggestion', models.TextField(blank=True, default='', help_text='What the supplier should do to fix this issue.')),
                ('line_number', models.PositiveSmallIntegerField(blank=True, help_text='Line item number if observation is item-level.', null=True)),
                ('included_in_email', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='inbound.inboundinvoice')),
            ],
            options={
                'db_table': 'inbound_observations',
                'ordering': ['severity', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('trn', models.CharField(db_index=True, help_text='UAE Tax Registration Number (15 digits).', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Contact email for observations.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('api_key_hash', models.CharField(blank=True, default='', help_text="SHA-256 hash of the supplier's API key.", max_length=64)),
                ('api_key_prefix', models.CharField(blank=True, default='', help_text='First 8 chars of key shown in UI for identification.', max_length=8)),
                ('whitelisted_email', models.EmailField(blank=True, default='', help_text='If set, inbound emails from this address are auto-accepted.', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('receiving_company', models.ForeignKey(help_text='Our company that receives invoices from this supplier.', on_delete=django.db.models.deletion.PROTECT, related_name='inbound_suppliers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'inbound_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inboundinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_invoices', to='inbound.supplier'),
        ),
        migrations.AddIndex(
            model_name='inboundinvoice',
            index=models.Index(fields=['supplier', 'status'], name='idx_inbound_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='inboundinvoice',
            index=models.Index(fields=['receiving_company', 'status'], name='idx_inbound_company_status'),
        ),
        migrations.AddIndex(
            model_name='inboundinvoice',
            index=models.Index(fields=['received_at'], name='idx_inbound_received_at'),
        ),
    ]
