# Generated by Django 6.0.4 on 2026-04-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='activation_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Platform user account for this supplier (inbound_supplier role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
