# Generated by Django 5.0.4 on 2026-08-01 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_company_legal_registration_authority"),
        ("inbound", "0002_supplier_user_activation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                help_text="Contact email for observations.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="trn",
            field=models.CharField(
                db_index=True,
                help_text="UAE Tax Registration Number (15 digits).",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("trn", "receiving_company"),
                name="inbound_supplier_unique_trn_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("email", "receiving_company"),
                name="inbound_supplier_unique_email_per_company",
            ),
        ),
    ]
