# Generated by Django 6.0.4 on 2026-04-28 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_company_alter_customer_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique token sent in the invite email link.', unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address of the invited buyer.', max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer record the buyer will be linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_invites', to='customers.customer')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_buyer_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Invite',
                'verbose_name_plural': 'Buyer Invites',
                'db_table': 'buyer_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(help_text='Customer record this buyer has access to.', on_delete=django.db.models.deletion.PROTECT, related_name='buyer_profiles', to='customers.customer')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buyer_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
                'db_table': 'buyer_profiles',
            },
        ),
    ]
