# Generated by Django 6.0.4 on 2026-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Invitation', 'verbose_name_plural': 'Company Invitations'},
        ),
        migrations.AlterModelOptions(
            name='onboardingdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Onboarding Document', 'verbose_name_plural': 'Onboarding Documents'},
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Personal note shown on the invite page.'),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='role',
            field=models.CharField(default='supplier', help_text='Role the new user will have within their company.', max_length=20),
        ),
    ]
