# Generated by Django 6.0.4 on 2026-05-26 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_companyinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='last_delivery_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('failed', 'Failed')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='link_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='send_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InvitationEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='onboarding.companyinvitation')),
            ],
            options={
                'db_table': 'invitation_email_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
