# Generated by Django 5.0.4 on 2026-07-30 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_aimessage"),
        ("companies", "0011_company_legal_registration_authority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIToolCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("arguments_json", models.JSONField(default=dict)),
                ("result_json", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("confirmed", "Confirmed"),
                            ("executed", "Executed"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        max_length=15,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tool_calls",
                        to="companies.company",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_call_logs",
                        to="ai_assistant.aimessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tool_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_tool_call_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "created_at"],
                        name="idx_aitool_company_created",
                    ),
                    models.Index(
                        fields=["tool_name", "status"], name="idx_aitool_name_status"
                    ),
                ],
            },
        ),
    ]
