# Generated by Django 5.0.4 on 2026-07-30 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_aitoolcalllog"),
        ("companies", "0011_company_legal_registration_authority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPendingAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_invoice", "Create Invoice"),
                            ("add_customer", "Add Customer"),
                            ("mark_paid", "Mark Paid"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payload_json",
                    models.JSONField(
                        help_text="Full proposed data for the action (e.g. draft invoice fields)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "result_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Pending actions auto-expire (e.g. 15 minutes) to avoid stale confirmations."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_pending_actions",
                        to="companies.company",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="ai_assistant.aiconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_pending_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_pending_actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="idx_aipending_user_status"
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="idx_aipending_company_status",
                    ),
                ],
            },
        ),
    ]
