# Generated by Django 5.0.4 on 2026-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_aipendingaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconversation",
            name="role_snapshot",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("supplier", "Supplier"),
                    ("accountant", "Accountant"),
                    ("viewer", "Viewer"),
                    ("inbound_supplier", "Inbound Supplier"),
                    ("buyer", "Buyer"),
                ],
                max_length=20,
            ),
        ),
    ]
