# Generated by Django 5.0.4 on 2026-07-25 08:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='UAE number in +971XXXXXXXXX format.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+971[0-9]{8,9}$', 'Enter a valid UAE phone number.')])),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Lead',
                'verbose_name_plural': 'Chat Leads',
                'db_table': 'chat_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
